### ISSUE TITLE
Deleting default workspace closes open non-default workspace

### ISSUE THREAD

**Issue by tukusejssirs** [Val95240/ProjectManager#11]
I had open two workspaces in two windows:
- `proj1:default`;
- `proj1:work1`.

I deleted `proj1:default`, which closed the windows in which it was open (as expected), but also closed `proj1:work1`. Fortunately, it was not deleted and I could simply re-open it.

I’d expect not to close any other project and/or workspace besides the one that is to be deleted.

**Comment by Val95240** [comment]
Closing all workspace attached to the project is necessary in order to make sure the workspace is deleted properly. The confirmation box for the deletion has a warning message concerning this issue reading "Warning: this will close any window opened containing files attached to the corresponding project".
However, I modified the code to reopen closed windows, so this should not be an issue anymore.
Tell me if you find something wrong !
